cache: apt
language: python
sudo: false
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
python:
  - 3.6
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - chmod 755 create_env.sh
install:
  - travis_retry . ./create_env.sh
  - python --version
  - which python
  - pip --version
  - travis_retry pip install coverage==4.0.3 nose pytest-pep8 pytest-cov python-coveralls
  - travis_retry python setup.py install
script:
  - nosetests -v --with-coverage --cover-tests --cover-package=intensity_normalization --ignore-files=intensity_normalization/utilities/robex.py tests
after_success:
  - coveralls

